### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by UlrikHD** [RikudouSage/LemmyAutomod#3]
The project is currently missing a license. Without one, admin teams for lemmy instances can't properly judge if they can use the software, it also creates uncertainty around future use and the possibility of forking the project for customising it for their instance's specific needs.

**Comment by RikudouSage** [comment]
Ah, forgot to include it, will do in a sec, if you want a few minutes head start, it's MIT.

**Comment by RikudouSage** [comment]
Done! Closed issue in ~4 minutes might be my personal record.
